### ISSUE TITLE
Broken link for ebook/PDF

### ISSUE THREAD

**Issue by shamrockspb** [semaphoreci-demos/semaphore-demo-cicd-kubernetes#18]
Hello,

I have registered on Semaphore site and got the link to PDF verson of the book.
Apparently this link is broken, kindly ask to check it:

![image](https://user-images.githubusercontent.com/12202712/115139055-854d9900-a038-11eb-84d7-08ec44871264.png)

Thanks!

Best regards,
Alex

**Comment by LarisaIoana08** [comment]
Hi Alex,

Many thanks for letting us know about this issue. I guess you tried to download it from here- https://semaphoreci.com/resources/cicd-docker-kubernetes, am I right?

**Comment by LarisaIoana08** [comment]
It seems the link is working for us. Can you please write to us at support@semaphoreci.com? We want to make sure you get the eBook. Thank you!
